# Generated by Django 4.2.18 on 2025-01-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt_post_updated_on_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field_2',
            field=models.CharField(default='Hello, World!'),
        ),
        migrations.AddField(
            model_name='post',
            name='field_3',
            field=models.CharField(null=True),
        ),
    ]
